server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
mybatis:
  type-aliases-package: com.work.information.entity

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10089/eureka